### ISSUE TITLE
Sending objects not just by newtonsoft serialization

### ISSUE THREAD

**Issue by ustaalon** [steven4547466/LC-API#27]
Hey, 

I was trying to work with the Library, while I was working on a mod that manipulates LethalCompany turret states, and I needed to send the LC Turret class via the network, but it failed because of serialization errors.

I don't have the error log right now, but it was related to Turret class extending Unity class that includes the gameObject property that can't be serialized (and some references loop etc)

**Comment by shells-above** [comment]
i'm doing the same thing in my program. i just send data over the network between all my processes (in my case it's the internal mod and my external 'control panel' as well as any other connected clients). i just send a packet id and then whatever data i want to send (currently selected mode, position, and anything else) as bytes. then i load the bytes into a custom data structure (using a custom deserializer that reads the expected type for the next field and reads that many bytes and hopes that the data is valid) for each object (i have ones for Turrets, Mines, Doors, Enemies, etc.) that just cleanly represents the received data.

you could also use json and then use the built in serializer to de/serialize your custom data structure after you've populated it with data from the Turret object, but i prefer not delimiting anything for smaller message sizes

there won't be any 'easy' way to serialize the entire Turret object that you pull from the game because some stuff just will not be able to be serialized by default like linked lists or similar. if you do want to do this  you'll need to make a custom serializer (or find some library that already has done this) that can handle each different 'case' in your target object (like those reference loops you mentioned)

**Comment by steven4547466** [comment]
I recommend using network object ids then getting the network object from the network objects map. `Turret` extends NetworkBehaviour, so it should be possible.
